CREATE TABLE TABLE_DATA_1
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_DATA_2
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_COLC1
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

SELECT * FROM TABLE_DATA_1;
SELECT * FROM TABLE_DATA_2;
SELECT * FROM TABLE_COLC;

INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');

INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');

select 
--delete
* from TABLE_COLC1
order by std_date;


MERGE INTO TABLE_COLC1 A
USING TABLE_DATA_1 B
ON (A.std_DATE = B.CREATE_DATE)
WHEN MATCHED THEN
    UPDATE SET a.check_data1 ='Y'
WHEN NOT MATCHED THEN
    INSERT VALUES (B.CREATE_DATE, 'Y', 'N');

MERGE INTO TABLE_COLC1 A
USING TABLE_DATA_2 B
ON (A.std_DATE = B.CREATE_DATE)
WHEN MATCHED THEN
    UPDATE SET a.check_data2 = 'Y'
WHEN NOT MATCHED THEN
    INSERT VALUES (B.CREATE_DATE, 'N', 'Y');
    


delete from table_colc;










